apiversion: v1
kind: Service
metadata:
  namespace: go-socket
  name: chat-server
spec:
  selector:
    app: chat-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP