version: '3.9'

services:
  chat-client:
    build:
      context: ./chat-client
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./chat-client:/app
      - /app/node_modules
    environment:
      - VUE_APP_API_URL=http://localhost:8080
    depends_on:
      - go-chat-server

  go-chat-server:
    build:
      context: ./go-chat-server
    ports:
      - "8080:8080"
    volumes:
      - ./go-chat-server:/app
    environment:
      - GO_ENV=development